data("USPersonalExpenditure")
print( summary(USPersonalExpenditure))
print(str(USPersonalExpenditure))
print(head(USPersonalExpenditure,5))
print(nrow(USPersonalExpenditure))
print(ncol(USPersonalExpenditure))